import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Clock,
  Command,
  Copy,
  Database,
  Download,
  ExternalLink,
  FileText,
  Filter,
  GitCompareArrows,
  History,
  Inbox,
  Info,
  Key,
  LayoutDashboard,
  Link as LinkIcon,
  ListChecks,
  Loader,
  LogOut,
  Monitor,
  Moon,
  MoreHorizontal,
  Pause,
  Pencil,
  Pin,
  Play,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Shield,
  Sun,
  Terminal,
  User,
  Users,
  X,
  Zap,
  type LucideProps,
} from 'lucide-react';
import type { FC } from 'react';

type IconComponent = FC<LucideProps>;

export const I: Record<string, IconComponent> = {
  layoutDashboard: LayoutDashboard,
  listChecks: ListChecks,
  activity: Activity,
  database: Database,
  gitCompareArrows: GitCompareArrows,
  settings: Settings,
  search: Search,
  plus: Plus,
  filter: Filter,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronsUpDown: ChevronsUpDown,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowRight: ArrowRight,
  more: MoreHorizontal,
  x: X,
  check: Check,
  play: Play,
  pause: Pause,
  refresh: RefreshCw,
  alertTriangle: AlertTriangle,
  alertCircle: AlertCircle,
  info: Info,
  clock: Clock,
  calendar: Calendar,
  user: User,
  users: Users,
  logOut: LogOut,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  command: Command,
  zap: Zap,
  loader: Loader,
  inbox: Inbox,
  fileText: FileText,
  externalLink: ExternalLink,
  copy: Copy,
  link: LinkIcon,
  shield: Shield,
  key: Key,
  history: History,
  terminal: Terminal,
  download: Download,
  pencil: Pencil,
  pin: Pin,
};
